### ISSUE TITLE
读取 init_msg 文件错误，gbk 无法解码

### ISSUE THREAD

**Issue by Sylphinford** [Cosmos01/aichat-chatGPT#13]
读取 init_msg 文件错误，gbk 无法解码

猫娘初始化 命令出现错误， 试着复制了别的咒语，也一样会错误。
好像是识别不了中文？

```
[2022-12-14 16:11:45,256 人工智障] INFO: Message 335966059 triggered init_neko by PrefixTrigger.
[2022-12-14 16:11:45,268 人工智障] ERROR: <class 'UnicodeDecodeError'> occured when init_neko handling message 335966059.
[2022-12-14 16:11:45,278 人工智障] ERROR: 'gbk' codec can't decode byte 0x80 in position 14: illegal multibyte sequence
Traceback (most recent call last):
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\msghandler.py", line 28, in handle_message
    await service_func.func(bot, event)
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\service.py", line 216, in wrapper
    return await func(bot, event)
  File "D:\XCW\hoshino_xcw\XCW\Hoshino\hoshino\modules\aichat-chatGPT\aichat.py", line 59, in init_neko
    neko = init_msg.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 14: illegal multibyte sequence
```

**Comment by Cosmos01** [comment]
感谢提交，已经改成utf-8编码，请更新代码并确定init_msg.txt文件为utf-8格式后再次尝试

**Comment by Sylphinford** [comment]
能行了。。感谢
