### ISSUE TITLE
import报错

### ISSUE THREAD

**Issue by Fhm-newbie** [Cosmos01/aichat-chatGPT#30]
[2023-03-28 11:37:10,686 nonebot] ERROR: Failed to import "hoshino.modules.aichat-chatGPT.client", error: module 'openai' has no attribute 'ChatCompletion'
[2023-03-28 11:37:10,686 nonebot] ERROR: module 'openai' has no attribute 'ChatCompletion'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin.py", line 253, in load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/HoshinoBot/hoshino/modules/aichat-chatGPT/client.py", line 6, in <module>
    class Client:
  File "/root/HoshinoBot/hoshino/modules/aichat-chatGPT/client.py", line 7, in Client
    chat = openai.ChatCompletion()
AttributeError: module 'openai' has no attribute 'ChatCompletion'

根据查询，说是较新版本的openai没有这个，应将 ChatCompletion改为 Completion

**Comment by Fhm-newbie** [comment]
然后我把client.py的那个调用改了之后确实能import了，但是艾特它只会回复发生错误：acreate

**Comment by Cosmos01** [comment]
感谢提醒，我感觉不如直接回退版本吧
pip3 install openai==0.27.0

**Comment by Fhm-newbie** [comment]
OK，我去退一下版本
